image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [555.715735370142, 0.0, 346.7216404016699,
         0.0, 555.6151962989876, 239.7857718290915,
         0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.3342237889048203, 0.23235110311312598, -0.0016514851587416134, 0.0003617765693851525, -0.11478954827236744]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [555.715735370142, 0.0, 346.7216404016699, 0.0,
         0.0, 555.6151962989876, 239.7857718290915, 0.0,
         0.0, 0.0, 1.0, 0.0]